import type { PresentationThemeSummary } from "@/types/presentation";

export const PRESENTATION_THEMES: PresentationThemeSummary[] = [
  {
    themeId: "corporate-clean",
    displayName: "Corporate Clean",
    colorPalette: {
      background: "#F8FAFC",
      surface: "#FFFFFF",
      textPrimary: "#0F172A",
      textSecondary: "#475569",
      accent: "#2563EB",
      accentSecondary: "#0EA5E9",
      danger: "#DC2626",
      mutedBorder: "#CBD5E1",
    },
    typography: {
      titleFontFamily: "Aptos",
      bodyFontFamily: "Aptos",
      titleFontSize: 30,
      subtitleFontSize: 19,
      bodyFontSize: 22,
      smallFontSize: 14,
    },
  },
  {
    themeId: "modern-minimal",
    displayName: "Modern Minimal",
    colorPalette: {
      background: "#FFFFFF",
      surface: "#FFFFFF",
      textPrimary: "#111827",
      textSecondary: "#6B7280",
      accent: "#111827",
      accentSecondary: "#9CA3AF",
      danger: "#DC2626",
      mutedBorder: "#E5E7EB",
    },
    typography: {
      titleFontFamily: "Aptos",
      bodyFontFamily: "Aptos",
      titleFontSize: 32,
      subtitleFontSize: 18,
      bodyFontSize: 21,
      smallFontSize: 13,
    },
  },
  {
    themeId: "executive-dark-accent",
    displayName: "Executive Dark Accent",
    colorPalette: {
      background: "#0F172A",
      surface: "#111827",
      textPrimary: "#F8FAFC",
      textSecondary: "#CBD5E1",
      accent: "#38BDF8",
      accentSecondary: "#A78BFA",
      danger: "#F87171",
      mutedBorder: "#334155",
    },
    typography: {
      titleFontFamily: "Aptos",
      bodyFontFamily: "Aptos",
      titleFontSize: 30,
      subtitleFontSize: 19,
      bodyFontSize: 21,
      smallFontSize: 14,
    },
  },
  {
    themeId: "ocean-blueprint",
    displayName: "Ocean Blueprint",
    colorPalette: {
      background: "#F3FAFF",
      surface: "#FFFFFF",
      textPrimary: "#0C4A6E",
      textSecondary: "#0369A1",
      accent: "#0284C7",
      accentSecondary: "#22D3EE",
      danger: "#DC2626",
      mutedBorder: "#BAE6FD",
    },
    typography: {
      titleFontFamily: "Aptos",
      bodyFontFamily: "Calibri",
      titleFontSize: 31,
      subtitleFontSize: 19,
      bodyFontSize: 21,
      smallFontSize: 14,
    },
  },
  {
    themeId: "sunrise-energy",
    displayName: "Sunrise Energy",
    colorPalette: {
      background: "#FFF8F1",
      surface: "#FFFFFF",
      textPrimary: "#7C2D12",
      textSecondary: "#C2410C",
      accent: "#EA580C",
      accentSecondary: "#FB923C",
      danger: "#DC2626",
      mutedBorder: "#FED7AA",
    },
    typography: {
      titleFontFamily: "Trebuchet MS",
      bodyFontFamily: "Arial",
      titleFontSize: 32,
      subtitleFontSize: 19,
      bodyFontSize: 21,
      smallFontSize: 13,
    },
  },
  {
    themeId: "forest-editorial",
    displayName: "Forest Editorial",
    colorPalette: {
      background: "#F5FBF7",
      surface: "#FFFFFF",
      textPrimary: "#14532D",
      textSecondary: "#3F6212",
      accent: "#15803D",
      accentSecondary: "#65A30D",
      danger: "#B91C1C",
      mutedBorder: "#CFE8D5",
    },
    typography: {
      titleFontFamily: "Georgia",
      bodyFontFamily: "Georgia",
      titleFontSize: 31,
      subtitleFontSize: 18,
      bodyFontSize: 20,
      smallFontSize: 13,
    },
  },
  {
    themeId: "plum-strategy",
    displayName: "Plum Strategy",
    colorPalette: {
      background: "#FCF7FF",
      surface: "#FFFFFF",
      textPrimary: "#4A044E",
      textSecondary: "#7E22CE",
      accent: "#A21CAF",
      accentSecondary: "#C084FC",
      danger: "#DC2626",
      mutedBorder: "#E9D5FF",
    },
    typography: {
      titleFontFamily: "Aptos",
      bodyFontFamily: "Helvetica",
      titleFontSize: 30,
      subtitleFontSize: 19,
      bodyFontSize: 21,
      smallFontSize: 13,
    },
  },
  {
    themeId: "ember-momentum",
    displayName: "Ember Momentum",
    colorPalette: {
      background: "#FFF5F5",
      surface: "#FFFFFF",
      textPrimary: "#7F1D1D",
      textSecondary: "#B45309",
      accent: "#DC2626",
      accentSecondary: "#F59E0B",
      danger: "#B91C1C",
      mutedBorder: "#FECACA",
    },
    typography: {
      titleFontFamily: "Verdana",
      bodyFontFamily: "Verdana",
      titleFontSize: 30,
      subtitleFontSize: 18,
      bodyFontSize: 20,
      smallFontSize: 13,
    },
  },
  {
    themeId: "graphite-boardroom",
    displayName: "Graphite Boardroom",
    colorPalette: {
      background: "#111111",
      surface: "#1C1C1C",
      textPrimary: "#F5F5F5",
      textSecondary: "#D4D4D8",
      accent: "#A3E635",
      accentSecondary: "#38BDF8",
      danger: "#F87171",
      mutedBorder: "#3F3F46",
    },
    typography: {
      titleFontFamily: "Helvetica",
      bodyFontFamily: "Arial",
      titleFontSize: 30,
      subtitleFontSize: 18,
      bodyFontSize: 20,
      smallFontSize: 13,
    },
  },
];

export function resolvePresentationTheme(themeId?: string | null) {
  return PRESENTATION_THEMES.find((theme) => theme.themeId === themeId) ?? PRESENTATION_THEMES[0];
}
